traceConfig:
  simpleType: probabilistic
  simpleRate: 0.9
consul:
  config:
    schema: http
    port: 8500
    address: 10.12.209.43
  discover:
    config:
      serviceName: python-consul-demo
      preferIpAddress: true
      healthCheckUrl: /api/health/check
      instanceId: python-consul-demo-1
app:
  config:
    serviceName: python-consul-demo
    serviceIpAddress: 10.12.140.173
    servicePort: 19300
trace:
  config:
    simpleType: probabilistic
    simpleRate: 1
    traceUDPAddress: 127.0.0.1
    traceUDPPort: 5775
